import 'dart:io' show Platform, File, Directory;
import 'package:flutter/foundation.dart' show kIsWeb;
import 'package:path_provider/path_provider.dart';
import 'package:intl/intl.dart';
import 'package:share_plus/share_plus.dart';
import 'package:permission_handler/permission_handler.dart';
import '../models/chat_message_model.dart';
import '../models/persona_model.dart';

class ExportService {
  Future<void> exportAndShareChat(Persona persona, List<ChatMessage> messages) async {
    final content = _generateChatContent(persona, messages);
    final fileName = "chat_export_${persona.name.replaceAll(' ', '_')}_${DateTime.now().millisecondsSinceEpoch}.txt";
    
    if (kIsWeb) {
      // On Web, we share the text directly since we can't easily write to a local file path
      await Share.share(
        content,
        subject: 'Chat Export: ${persona.name}',
      );
      return;
    }

    // Mobile Logic
    Directory? directory;
    if (Platform.isAndroid) {
      directory = Directory('/storage/emulated/0/Download');
      if (!await directory.exists()) {
        directory = await getExternalStorageDirectory();
      }
      
      var status = await Permission.manageExternalStorage.request();
      if (!status.isGranted) {
        status = await Permission.storage.request();
      }
    } else if (Platform.isIOS) {
      directory = await getApplicationDocumentsDirectory();
    }

    if (directory == null) throw Exception("Could not access storage directory");

    final file = File('${directory.path}/$fileName');
    await file.writeAsString(content);
    
    await Share.shareXFiles(
      [XFile(file.path)],
      text: 'Chat exported with ${persona.name}',
      subject: 'Chat Export: ${persona.name}',
    );
  }

  String _generateChatContent(Persona persona, List<ChatMessage> messages) {
    final buffer = StringBuffer();

    buffer.writeln("Chat Export: ${persona.name}");
    buffer.writeln("Tone: ${persona.tone}");
    buffer.writeln("Date: ${DateFormat.yMMMMEEEEd().format(DateTime.now())}");
    buffer.writeln("--------------------------------------------------\n");

    for (final msg in messages) {
      final time = DateFormat('HH:mm').format(msg.timestamp);
      final sender = msg.isUser ? "You" : persona.name;

      buffer.writeln("[$time] $sender:");
      buffer.writeln(msg.text);
      buffer.writeln("");
    }

    buffer.writeln("--------------------------------------------------");
    buffer.writeln("Generated by PersonaChat");
    return buffer.toString();
  }
}
